
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
	/* terminals */
	public static final int ELSE = 17;
	public static final int IDENT = 15;
	public static final int PLUS = 11;
	public static final int RBRACE = 4;
	public static final int RPAREN = 7;
	public static final int EQUAL = 12;
	public static final int SEMI = 5;
	public static final int RETURN = 10;
	public static final int IF = 16;
	public static final int LPAREN = 6;
	public static final int LBRACE = 3;
	public static final int COMMA = 8;
	public static final int EOF = 0;
	public static final int NUMBER = 14;
	public static final int PROG = 2;
	public static final int PRINT = 9;
	public static final int error = 1;
	public static final int VOID = 13;

	public static final int FOR = 24;

	public static final int BREAK = 18;

	public static final int READ = 19;

	public static final int CLASS = 20;
	public static final int ABSTRACT = 21;

	public static final int CONST = 22;

	public static final int NEW = 23;
	
	public static final int CONTINUE = 25;

	public static final int EXTENDS = 26;
	
	public static final int LSQUARE = 27;
	public static final int RSQUARE = 28;
	
	public static final int MINUS = 29;
	public static final int MUL = 30;
	public static final int DIV = 31;
	public static final int MOD = 32;
	
	public static final int EQ = 33;
	public static final int NOTEQ = 34;
	public static final int GRT = 35;
	public static final int GRTEQ = 36;
	public static final int LESS = 37;
	public static final int LESSEQ = 38;
	public static final int AND = 39;
	public static final int OR = 40;
	
	public static final int INCR = 41;
	public static final int DECR = 42;

	public static final int DOT = 43;

	public static final int BOOLCONST = 44;
	public static final int CHARCONST = 45;
}
